# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2,jekyll-gist]

pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Riyas P
description: "Portfolio"
keywords: "riyas, riyasp, riyasyash, riyas p"
url: riyasyash.github.io
baseurl: ""

repo: https://github.com/riyasyash
disqus_shortname: "riyasyash"
disqus_site_shortname: "riyashyash"
site:
  repo: https://github.com/riyasyash
# Author settings
author:
  name: Riyas P
  job: I build 'stuff' with
  bio: "Fullstack Developer @ Lightwing.io"
  thumb: /images/author.png
  email: riyasyash@gmail.com
  url: https://riyasyash.me/
  gitlab: https://gitlab.com/riyasyash
  github: https://github.com/riyasyash
  twitter: https://twitter.com/riyasyash
  # facebook: https://facebook.com/riyas.subair.73
  medium: https://medium.com/@riyasyash
  linkedin: https://linkedin.com/in/riyasyash
  instagram: https://www.instagram.com/riyasyash/

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog
  - slug: lab
    title: Lab

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]

gist:
  noscript: false
  color: white
lab:
  - name: Shrink Ray
    description: A URl shortening service written in Golang and presented via Angular
    url: https://shrinkray.riyasyash.me
    img: https://github.com/riyasyash/shrink-ray/raw/master/Screenshot.png
    code: https://github.com/riyasyash/shrink-ray
    tools: ["Go","Angular","HTML","CSS"]
  - name: HeimdallR
    description: A raspberry-pi based smart surveillance assistant
    url: https://riyasyash.me
    # img: https://picsum.photos/200/300?grayscale&&blur=4
    code: https://github.com/riyasyash/heimdallr
    tools: ["Python","Flutter","Dart"]
  - name: Portfolio
    description: My personal portfolio website
    url: https://riyasyash.me
    # img: https://picsum.photos/200/300?grayscale&&blur=4
    code: https://github.com/riyasyash/portfolio
    tools: ["Jekyll","HTML","CSS"]

experience:
  - start_date: "May 2016"
    org: "Sahaj Software Solutions PVT LTD"
    org_url: "https://sahaj.ai"
    position: "Solution Consultant"
  - start_date: "Aug 2020"
    org: "Lightwing"
    org_url: "https://lightwing.io"
    position: "Fullstack Developer"
  # - start_date: "Nov 2020"
  #   org: "Harness R&D Labs India"
  #   org_url: "https://harness.io"
  #   position: "Software Engineer"
  